[package]
name = "sddrsc"
edition = "2021"

[[bin]]
name = "sddrsc"
path = "main.rs"

[dependencies]
tracing-subscriber = "0.3"
tracing = "0.1"
clap = { version = "4.5.4", features = ["derive"] }
sddrs = { path = "../sdd-rs-lib" }
