repos:
- repo: local
  hooks:
  - id: fmt
    name: cargo fmt --check
    description: Check formatting of files with cargo fmt
    language: rust
    entry: cargo fmt --check --
    files: \.rs$
    args: []
  - id: check
    name: cargo check
    description: Check package and dependencies for errors
    language: rust
    entry: cargo check
    files: \.rs$
    pass_filenames: false
  - id: clippy
    name: cargo clippy
    description: Lint with Clippy
    language: rust
    entry: cargo clippy --all-features --tests --benches -- -Dclippy::all -Dclippy::pedantic
    files: \.rs$
    pass_filenames: false
  - id: test
    name: cargo test
    description: Run unit tests
    language: rust
    entry: cargo test
    files: \.rs$
    pass_filenames: false
