[workspace]
members = ["bin", "benchmarks", "sdd-rs-lib"]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
mutable_key_type = "allow"
module_inception = "allow"
