[package]
name = "sdd-benchmarks"
edition = "2021"

[[bin]]
name = "benchmarks"
path = "main.rs"

[dependencies]
rsdd = { git = "https://github.com/neuppl/rsdd" }
clap = { version = "4.5.4", features = ["derive"] }
